apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    environment: development
    purpose: webapp
    cost-center: engineering

---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    purpose: webapp
    cost-center: engineering

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    purpose: webapp
    cost-center: engineering