apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
stringData:
  db_username: webapp_user
  db_password: super_secret_password_123
  jwt_secret: jwt_signing_key_xyz789
  api_key: external_api_key_abc123